import { supabase } from './supabase';

export interface TranslationValidationResult {
  id: string;
  gameId: string;
  gameName: string;
  pointId: string;
  pointTitle: string;
  language: string;
  missingFields: string[];
  createdAt: string;
}

/**
 * Fetch translation validation results from Supabase
 * These are generated by the daily Edge Function validator
 */
export const fetchTranslationValidationResults = async (): Promise<TranslationValidationResult[]> => {
  try {
    const { data, error } = await supabase
      .from('translation_validation_results')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('[Translation Validation] Error fetching results:', error);
      return [];
    }

    return (data || []).map(row => ({
      id: row.id,
      gameId: row.game_id,
      gameName: row.game_name,
      pointId: row.point_id,
      pointTitle: row.point_title,
      language: row.language,
      missingFields: Array.isArray(row.missing_fields) ? row.missing_fields : [],
      createdAt: row.created_at,
    }));
  } catch (error) {
    console.error('[Translation Validation] Unexpected error:', error);
    return [];
  }
};

/**
 * Trigger the translation validation Edge Function manually
 * This can be called from the admin UI to run validation on-demand
 */
export const triggerTranslationValidation = async (): Promise<{ success: boolean; error?: string }> => {
  try {
    const supabaseUrl = localStorage.getItem('SUPABASE_URL') || 'https://yktaxljydisfjyqhbnja.supabase.co';
    const edgeFunctionUrl = `${supabaseUrl}/functions/v1/translation-validator`;

    console.log('[Translation Validation] Triggering validation...');

    const response = await fetch(edgeFunctionUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: 'Unknown error' }));
      console.error('[Translation Validation] Edge Function error:', error);
      return { success: false, error: error.error || 'Validation failed' };
    }

    const result = await response.json();
    console.log('[Translation Validation] Validation complete:', result);

    return { success: true };
  } catch (error) {
    console.error('[Translation Validation] Error triggering validation:', error);
    return { success: false, error: String(error) };
  }
};

/**
 * Group validation results by game for easier display
 */
export const groupResultsByGame = (results: TranslationValidationResult[]): Record<string, TranslationValidationResult[]> => {
  const grouped: Record<string, TranslationValidationResult[]> = {};

  results.forEach(result => {
    if (!grouped[result.gameId]) {
      grouped[result.gameId] = [];
    }
    grouped[result.gameId].push(result);
  });

  return grouped;
};

/**
 * Count total missing translations
 */
export const countMissingTranslations = (results: TranslationValidationResult[]): number => {
  return results.length;
};

/**
 * Count missing translations by language
 */
export const countByLanguage = (results: TranslationValidationResult[]): Record<string, number> => {
  const counts: Record<string, number> = {};

  results.forEach(result => {
    counts[result.language] = (counts[result.language] || 0) + 1;
  });

  return counts;
};
